Do not emit process title to stdout
simonhaenisch/md-to-pdf pull request #179
Opened 2023-03-24 18:46 UTC by ltvolks

Redirecting stdout into a target file is a common cli operation.

```sh
cat file.md | md-to-pdf > path/to/output.pdf
```

When the cli sets the process title, the helper util emits to `stdout`, which prepends a few bytes before the standard `%PDF-#.#` comment in the final PDF.

Most readers seem to ignore these bytes, but it's common for some tools to read a few bytes to determine if a file is a PDF.

Omitting the title seems like a sane strategy as I don't think it serves any useful purpose beyond cosmetic.

2023-03-25 18:25 UTC, simonhaenisch commented on src/cli.ts
> +	setProcessTitle('md-to-pdf');
Can you just change this line to

```suggestion
	process.title = 'md-to-pdf';
```

and get rid of the helper and test?

No need to keep it if it's the only thing it does i think (:

2023-03-25 18:27 UTC, simonhaenisch requested changes
Thanks for finding this, I somehow wasn't even aware of this terminal title via stdout thing anymore when I added the stdio mode 😅

Please see the comment I dropped. Alternatively could set the terminal title only if `process.stdin` is empty, but yeah not sure it's worth the effort.

2023-04-04 16:39 UTC, ltvolks commented
Updated per request, thanks for considering this change.

2023-04-04 18:06 UTC, simonhaenisch approved these changes

2023-04-04 18:07 UTC, merged